# Generated by Django 4.2.2 on 2023-06-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('usergroup', models.CharField(choices=[('AD', 'Admin'), ('ST', 'Simpleton')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PA', 'Pending approval'), ('WP', 'Work in progress'), ('CM', 'Completed')], default='PA', max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='src.user')),
            ],
        ),
    ]
